const actionsTypes = {
    "FETCH_JOB_DETAILS_REQUEST": "FETCH_JOB_DETAILS_REQUEST",
    "FETCH_JOB_DETAILS_SUCCESS": "FETCH_JOB_DETAILS_SUCCESS",
    "FETCH_JOB_DETAILS_FAILURE": "FETCH_JOB_DETAILS_FAILURE",
    "UPDATE_FILTER_SETTINGS":"UPDATE_FILTER_SETTINGS",
    "UPDATE_FILTER_LIST":"UPDATE_FILTER_LIST"
};

export default actionsTypes;