const actionsTypes = {
    "FETCH_JOB_DETAILS_REQUEST": "FETCH_JOB_DETAILS_REQUEST",
    "FETCH_JOB_DETAILS_SUCCESS": "FETCH_JOB_DETAILS_SUCCESS",
    "FETCH_JOB_DETAILS_FAILURE": "FETCH_JOB_DETAILS_FAILURE",
};

export default actionsTypes;